# https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/tracking_servers.txt
# bytedance tracking
DOMAIN-SUFFIX,os-mon.zijieapi.com
DOMAIN-SUFFIX,pc-mon.zijieapi.com
# doubao ime
DOMAIN-SUFFIX,ime.doubao.com
DOMAIN-SUFFIX,ime-igw.doubao.com
